[from]
chain = "polygon"
datasource = "big_query"
dapp_type = "aave"
start = "2024-06-01"
end = "2024-06-30"

[from.aave]
tokens = [# address of erc20 token which avialable on aave
    "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619",
    "0x2791bca1f2de4661ed88a30c99a7a9449aa84174"
]

[from.big_query]
auth_file = "bigquerykey.json" # google bigquery auth file

[to]
type = "minute"
save_path = "./sample" # save data to this folder
keep_raw = true